# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Run-of River Hydropower
author: Dan Kovacek, P.Eng.
email: dan@dkhydrotech.com
logo: img/dkht_logo.jpg
description: >-
  Content for presentation to BCIT EENG-8435 - District Energy Systems

baseurl: "content"
url: "https://dankovacek.github.io/run_of_river_intro"


# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

parse:
  myst_extended_syntax: true

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/dankovacek/run_of_river_intro  # Online location of your book
  path_to_book: content  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true


